import { FIREBASE_ERROR_TYPES } from '@/constants/firebase-error-types'

export const getFirebaseAuthErrorMessage = (error) => {
	switch (error) {
		case FIREBASE_ERROR_TYPES.AUTHENTICATION_ACTION_TYPES
			.INVALID_LOGIN_CREDENTIALS:
			return FIREBASE_ERROR_TYPES.AUTHENTICATION_ACTION_TYPES
				.INVALID_LOGIN_CREDENTIALS_MESSAGE
		case FIREBASE_ERROR_TYPES.AUTHENTICATION_ACTION_TYPES
			.TOO_MANY_ATTEMPTS_TRY_LATER:
			return FIREBASE_ERROR_TYPES.AUTHENTICATION_ACTION_TYPES
				.TOO_MANY_ATTEMPTS_TRY_LATER_MESSAGE
		default:
			return FIREBASE_ERROR_TYPES.AUTHENTICATION_ACTION_TYPES
				.DEFAULT_MESSAGE
	}
}
