name: Track Repo Clones

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour (adjust as needed)
  workflow_dispatch:

jobs:
  track-clones:
    runs-on: ubuntu-latest
    steps:
      - name: Get Repo Traffic Data
        id: traffic
        run: |
          curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
               -H "Accept: application/vnd.github+json" \
               https://api.github.com/repos/${{ github.repository }}/traffic/clones > clones.json
          
          cat clones.json

      - name: Send Notification (Optional)
        if: always()
        run: |
          CLONE_COUNT=$(jq '.count' clones.json)
          UNIQUE_COUNT=$(jq '.uniques' clones.json)

          echo "Total Clones: $CLONE_COUNT"
          echo "Unique Cloners: $UNIQUE_COUNT"

          # Example: Send to Discord webhook (replace YOUR_WEBHOOK_URL)
          if (( CLONE_COUNT > 0 )); then
            curl -H "Content-Type: application/json" \
              -X POST \
              -d "{\"content\": \"🚨 Repo cloned! Total: $CLONE_COUNT, Unique: $UNIQUE_COUNT\"}" \
              ${{ secrets.DISCORD_WEBHOOK }}
          fi
