name: Cypress - Run Component Tests

on:
    push:
        branches:
            - main
        paths:
            - 'src/**/*.cy.{js,jsx,ts,tsx}'
            - 'src/**/*.jsx'
            - 'src/**/*.tsx'
            - 'cypress.config.*'
            - 'package.json'
    pull_request:
        branches:
            - main
    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '22'
                  cache: 'npm'

            - name: Install dependencies
              run: npm install

            - name: Run Cypress Component Tests
              uses: cypress-io/github-action@v6
              with:
                  component: true
