name: GitHub - Auto Label Pull Requests

on:
    pull_request:
        types: [opened, synchronize, reopened]

permissions:
    contents: read
    pull-requests: write
    issues: write

jobs:
    add-labels:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Apply labels to PR
              uses: actions/labeler@v4
              with:
                  repo-token: '${{ secrets.GITHUB_TOKEN }}'
                  configuration-path: '.github/labeler.yml'
                  sync-labels: true
