name: Run Unit Tests (Vitest)

on:
    push:
        branches:
            - main
        paths:
            - 'src/**'
            - 'package.json'
            - 'vitest.config.*'
            - '**/*.test.{js,jsx,ts,tsx}'
            - '**/*.spec.{js,jsx,ts,tsx}'
    pull_request:
        branches:
            - main
    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    test:
        name: Run Unit Tests
        runs-on: ubuntu-latest
        timeout-minutes: 10

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '22'
                  cache: 'npm'

            - name: Install dependencies
              run: npm install

            - name: Run Unit Tests
              run: npm run vitest:run
              timeout-minutes: 3

            - name: Generate Coverage Report
              run: npm run vitest:coverage -- --run
              timeout-minutes: 8

            - name: Upload Coverage Reports
              uses: actions/upload-artifact@v4
              if: always()
              with:
                  name: coverage-reports-${{ github.run_number }}
                  path: coverage/
                  retention-days: 30
